export { default as footerIcon } from '../assets/imgs/FooterIcon.svg'
export { default as swiper } from '../assets/imgs/intro.png'
export { default as Divider } from '../assets/imgs/Divider.svg'
export { default as Computers } from '../assets/imgs/Computers.svg'
export { default as Camera } from '../assets/imgs/Camera.svg'
export { default as Gaming } from '../assets/imgs/Gaming.svg'
export { default as SmartWatch } from '../assets/imgs/SmartWatch.svg'
export { default as Phones } from '../assets/imgs/Phones.svg'
export { default as HeadPhones } from '../assets/imgs/HeadPhones.svg'
export { default as platstation } from '../assets/imgs/platstation.svg'
export { default as women } from '../assets/imgs/women.svg'
export { default as parfume } from '../assets/imgs/parfume.svg'
export { default as speaker } from '../assets/imgs/speaker.svg'
export { default as card_1 } from '../assets/imgs/card_1.svg'
export { default as card_2 } from '../assets/imgs/card_2.svg'
export { default as card_3 } from '../assets/imgs/card_3.svg'
export { default as registerImg } from '../assets/imgs/registerImg.png'
export { default as account } from '../assets/imgs/account.svg'
export { default as accountWhite } from '../assets/imgs/accountWhite.svg'
export { default as logout } from '../assets/imgs/logout.svg'
export { default as cartWithProducts } from '../assets/imgs/cartWithProducts.svg'
export { default as car } from '../assets/imgs/car.svg'
export { default as delivry } from '../assets/imgs/delivry.svg'
export { default as girls } from '../assets/imgs/about__img.svg'
export { default as ManageAccount } from '../assets/imgs/ManageAccount.svg'
export { default as add } from '../assets/imgs/plus.png'


